---
title: first post
author: ubisoon
date: '2018-12-27'
slug: first-post
categories:
  - R
tags:
  - R Markdown
---

```{r }
set.seed(2018)

cendata <- function(n=1000, beta0=10, beta1=1, sigma2=0.7, c=c, x=NULL, xdist=rbinom) {
  if (is.null(x)) {
    x <- xdist(n, size=1, p=0.5)
    x <- x/sd(x) # standardize to have sd of 1
  }
  eps <- rnorm(n, mean=0, sd=sqrt(sigma2)) # Transform eps to have std dev of sigma
  y.star <- beta0 + beta1*x + eps
  y <- ifelse(y.star<c, y.star, c) # right-censored at c
  return( data.frame(y=y, x=x, eps=eps) )
}
```
```{r}
## try data
n <- 1000
x <- rbinom(n=n, size=1, p=0.5) # x is a treatment dummy variable here (education)
dta <- cendata(n=1000,x=x,c=12) # censoring point (c) = 12
hist(exp(dta$y), breaks = 50) # Suppose that y is ln(income). it seems like income distribution
summary(lm(y~x, data=dta))
```

```{r}
dta.larger <- cendata(n=1000,x=x,c=11)
hist(exp(dta.larger$y), breaks = 50)
summary(lm(y~x, data=dta.larger))$coef
# lowing c -> more censoring occurs -> more biased estimates
```
